[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/politicas"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/libro-de-reclamaciones"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
